### ISSUE TITLE
file_get_contents(): https://

### ISSUE THREAD

**Issue by abedputra** [hok00age/codeigniter-recaptcha#2]
My PHP.ini
allow_url_fopen = ON
allow_url_include = ON

but still error:
Message: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0

Can you help me?

**Comment by alexanderglueck** [comment]
Try calling `ini_set('allow_url_fopen', 1);` somewhere in your code before this gets executed. 
If this does not help, have a look at this similar StackOverflow answer I found: [StackOverflow Answer](https://stackoverflow.com/a/21945398/2666199)

**Comment by abedputra** [comment]
Hi,
Thanks for helped, but right now, I not used this library again.
I use cURL and manual documentation ReCaptcha from google.
Anyway thanks for helped.
